{
  # These are the rules to set what Markdownlint is looking for
  "default": false,
  "MD003": { "style": "atx_closed" },
  "MD007": { "indent": 4 },
  "no-hard-tabs": false,
  "whitespace": false,
  
  # These lines ensure what folder(s) Markdownlint should be avoiding
  "markdownlint.ignore": [
        "mtl_facilitate_workgroup",
        "ees_workgroup/master_brochures"
    ]
    
}
