{
  # These are the rules to set what Markdownlint is looking for
  "default": false,
  "MD003": { "style": "atx_closed" },
  "MD007": { "indent": 4 },
  "no-hard-tabs": false,
  "whitespace": false

    
}
